server:
  port: 8001
spring:
  application:
    name: multitenant
  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/medium_multi_tenant
    username: postgres
    password: postgres
  flyway:
    schemas:
      - cliente01
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
